// <auto-generated />
using System;
using BuscarReciclaveis.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuscarReciclaveis.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuscarReciclaveis.Domain.Entidades.CategoriasReciclaveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TextoCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriasReciclaveis");
                });

            modelBuilder.Entity("BuscarReciclaveis.Domain.Entidades.ItemsReciclaveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCategoriasReciclaveis")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TextoItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriasReciclaveis");

                    b.ToTable("ItemsReciclaveis");
                });

            modelBuilder.Entity("BuscarReciclaveis.Domain.Entidades.ItemsReciclaveis", b =>
                {
                    b.HasOne("BuscarReciclaveis.Domain.Entidades.CategoriasReciclaveis", "CategoriasReciclaveis")
                        .WithMany()
                        .HasForeignKey("IdCategoriasReciclaveis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriasReciclaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
